name: Build

on:
  # New version.
  push:
    tags:
      - v*

  # Manual trigger.
  workflow_dispatch:

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
      volumes:
        - /:/hostfs

    steps:
      - name: Maximize build space
        run: |
          echo "Before:"
          df -h
          rm -rf /hostfs/usr/share/dotnet
          rm -rf /hostfs/usr/local/lib/android
          rm -rf /hostfs/opt/ghc
          rm -rf /hostfs/opt/cabal
          rm -rf /hostfs/opt/swift
          rm -rf /hostfs/opt/pyenv
          rm -rf /hostfs/usr/local/.ghcup
          rm -rf /hostfs/opt/hostedtoolcache/CodeQL
          rm -rf /hostfs/opt/hostedtoolcache/node
          rm -rf /hostfs/opt/hostedtoolcache/go
          rm -rf /hostfs/opt/hostedtoolcache/php
          rm -rf /hostfs/opt/hostedtoolcache/Ruby
          rm -rf /hostfs/opt/hostedtoolcache/Python
          rm -rf /hostfs/usr/share/doc \
            /hostfs/usr/share/man \
            /hostfs/usr/share/info \
            /hostfs/usr/share/lintian \
            /hostfs/usr/share/locale/* \
            /hostfs/usr/share/locale-langpack/*
          echo "After:"
          df -h

      - name: Set dynamic env vars
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "REPO_NAME_LOWER=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          curl https://download.docker.com/linux/static/stable/x86_64/docker-28.1.1.tgz --output ./docker.tgz
          tar xzvf docker.tgz
          mv docker/* /usr/bin

          curl -L https://github.com/regclient/regclient/releases/download/v0.8.3/regctl-linux-amd64 > regctl
          chmod 755 regctl
          mv regctl /usr/bin

      - name: NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Run local server
        uses: JarvusInnovations/background-action@v1
        with:
          working-directory: downloadserver
          wait-on: http-get://localhost:5173/info
          run: |
            npm ci
            npm run start

      - name: Test local server
        run: curl http://localhost:5173/info

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          branch: stable
          manifest-path: ${{ env.REPO_NAME }}.yml
          cache: false
          restore-cache: false
          build-bundle: false

      - name: Clear
        run: |
          df -h
          pwd
          ls
          rm -rf .flatpak-builder
          rm -rf build

      - name: Build image
        run: |
          df -h
          flatpak build-bundle /hostfs/mnt/repo ./image $REPO_NAME stable --oci

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: artifacts.flat.software
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push
        run: |
          echo "Update index."
          jq '.manifests[0].annotations["org.opencontainers.image.ref.name"] = "repo/$REPO_NAME_LOWER:stable"' ./image/index.json > tmp.json
          mv tmp.json ./image/index.json

          echo "Get variables."
          version=$(xmllint --xpath 'string(//release[1]/@version)' $REPO_NAME.metainfo.xml)

          echo "Copy latest."
          regctl image copy ocidir://image:stable "artifacts.flat.software/flatpaks/$REPO_NAME_LOWER:latest" -v debug

          echo "Copy stable."
          regctl image copy ocidir://image:stable "artifacts.flat.software/flatpaks/$REPO_NAME_LOWER:stable"

          echo "Copy $version."
          regctl image copy ocidir://image:stable "artifacts.flat.software/flatpaks/$REPO_NAME_LOWER:$version"
