name: Test trigger

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website deploy
        run: gh workflow run deploy.yml --repo flat-software/website --ref main
        env:
          GH_TOKEN: ${{ secrets.REGISTRY_DEPLOY_TOKEN }}
